name: LDAL-Own

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # 允许手动触发工作流
  # schedule:
  #   - cron: '0 * * * *'  # 每小时运行一次，UTC时间

jobs:
  run-LDAL-Own:
    runs-on: macos-latest  # 使用 macOS 环境

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 最新稳定的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pytz fake_useragent

    - name: Run LDAL-Own
      run: python LDAL-Own.py
