name: Python Selenium Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 最新稳定的 Python 版本

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pytz fake_useragent

    - name: Run Python script
      run: python LDAL.py
